server {
  listen 80;
  server_name all.keepthinking.me;

  location /.well-known/acme-challenge/ {
    root /var/www/certbot;
    default_type text/plain;
  }

  location / {
    return 301 https://$host$request_uri;
  }
}

server {
  listen 443 ssl http2;
  server_name all.keepthinking.me;

  ssl_certificate /etc/letsencrypt/live/all.keepthinking.me/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/all.keepthinking.me/privkey.pem;
  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_prefer_server_ciphers on;
  ssl_session_cache shared:SSL:10m;

  root /home/ubuntu/product_site_static/current;
  index index.html;

  location = / {
    try_files /all/index.html =404;
  }

  location = /hikiki.html {
    return 301 /hikiki/;
  }

  location /hikiki/ {
    try_files $uri $uri/ /hikiki/index.html;
  }

  location / {
    try_files $uri $uri/ /all/index.html;
  }
}
