# 奇奇漫游记 - 开发环境配置
# 用于本地开发调试，优化开发体验
# 注意：日志配置独立处理，通过环境变量 LOG_LEVEL 和 LOG_COLORS 控制

# ==========================================
# 服务器配置
# ==========================================
[server]
# 开发环境绑定本地地址
host = "127.0.0.1"
port = 8081

# 开发环境CORS配置：包含常用开发端口
cors_origins = [
    "http://localhost:5173",      # Vite默认端口
    "http://127.0.0.1:3000",      # API服务端口
    "http://localhost:3000",      # API服务端口
    "http://127.0.0.1:3000",      # 本地回环地址
    "http://127.0.0.1:5173",      # 本地回环地址（Vite）
    "http://localhost:4173",      # Vite预览端口
    "http://localhost:3001"       # 备用前端端口
]

# ==========================================
# 安全配置
# ==========================================
[security]
# 开发环境JWT过期时间更长，减少重复登录
jwt_expiration_hours = 72
