# 奇奇漫游记 - 预发布环境配置
# 用于测试服务器，模拟生产环境但保留调试能力
# 注意：日志配置独立处理，自动使用生产级日志配置

# ==========================================
# 服务器配置
# ==========================================
[server]
# 预发布环境绑定所有接口，便于外部访问测试
host = "127.0.0.1"
port = 8001

# 预发布环境CORS配置：仅允许测试域名
cors_origins = [
    "https://test.qiqimanyou.com",      # 测试环境前端
    "https://staging.qiqimanyou.com",   # 预发布环境前端
    "https://dev.qiqimanyou.com",       # 开发环境前端
    "http://localhost:3000",            # 本地测试（可选）
    "http://localhost:5173"             # 本地Vite测试（可选）
]

# ==========================================
# 安全配置
# ==========================================
[security]
# 预发布环境JWT过期时间与生产环境一致
jwt_expiration_hours = 24
