# 奇奇漫游记 - 生产环境配置
# 用于正式部署，注重安全性和性能
# 注意：日志配置独立处理，自动使用生产级日志配置

# ==========================================
# 服务器配置
# ==========================================
[server]
# 生产环境绑定所有接口，用于Docker容器或云服务器
host = "0.0.0.0"
port = 8001

# 生产环境CORS配置：仅允许正式域名，严格控制安全
cors_origins = [
    "http://keepthinking.me",
    "https://keepthinking.me",          # 主要访问域名
    "https://www.keepthinking.me",         # 主域名
    "http://www.keepthinking.me",       # WWW域名
    "http://app.keepthinking.me",       # 应用域名
    "http://admin.keepthinking.me",     # 管理后台域名
    "http://82.156.34.186:8080"         # web IP域名
]

# ==========================================
# 安全配置
# ==========================================
[security]
# 生产环境JWT过期时间适中，平衡安全性与用户体验
jwt_expiration_hours = 24
